<script src="/javascripts/jquery.validationEngine-pl.js" type="text/javascript" charset="utf-8"></script>
<script src="/javascripts/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>

<script>
	jQuery(document).ready(function(){	
		jQuery('#new_seat').validationEngine('attach', { validationEventTrigger: 'submit'});
	});
</script>

<%= form_for @seat, :validate => true do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2>Zaszły następujące nieprawidłowości:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"Id Sali" %><br />
    <%= f.text_field :room_id , :value => @seat.room.id %>
    
  </div>
  
  <div class="field">
    <%= f.label :Rząd %><br />
    <%= f.text_field :row, :class => 'validate[required,maxSize[2],custom[onlyLetterSp]] text-input' %>
  </div>
  <div class="field">
    <%= f.label :Kolumna %><br />
    <%= f.text_field :collumn, :class => 'validate[custom[integer]' %>
  </div>
  <div class="actions">
    <%= f.submit "Dodaj"%>
  </div>
<% end %>
